### ISSUE TITLE
Control with 24 buttons is not working!

### ISSUE THREAD

**Issue by eekthecatJP** [AntiMicroX/antimicrox#770] opened 2023-04-16 02:43 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

the elecom joystick with 24 buttons (Elecom JC-DUX60BK Gamepad - https://www.amazon.co.jp/gp/product/B01NBKEGOX/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&th=1), is not mapping correctly, it is mapped like the Xbox, only using the number of buttons on the XBOX joystick, so it is not possible to use the 24 buttons!

This does not happen in the previous version 2.24 and 2.23, where all buttons can be mapped normally!

### Expected Behavior

hopefully all 24 buttons can be mapped to keyboard keys like they used to!

### Steps To Reproduce

1 - get the 24 button Elecom JC-DUX60BK Gamepad
2 - try map the extra keys, 

### Anything else?

apparently the antimicro uses the XBOX joystick as a base, this makes it impossible to use controls with more buttons than the XBOX has, since the predecessor does not have this limitation, being able to use any type of joystick, with 24 buttons or more!

**Comment by pktiuk** [comment] 2023-04-16 11:53
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/694

**Closed by pktiuk** 2023-04-16 11:53 UTC
Labels: bug
