### ISSUE TITLE
AntiMicroX unable to bind Xbox Series X controller Share button

### ISSUE THREAD

**Issue by blackwind** [AntiMicroX/antimicrox#307] opened 2021-12-02 23:51 UTC
One of the primary additions to Xbox Series X controllers over the classic Xbox One controller is a Share button:

![share](https://user-images.githubusercontent.com/889881/144520667-53c29a26-eb2c-435a-b83a-f4a62fa18778.jpg)

In AntiMicro, Xbox Series X controllers connected via Bluetooth show up as two separate devices:

![am1](https://user-images.githubusercontent.com/889881/144520078-490c787d-6cba-4e44-9b54-057315b08253.png)
![am2](https://user-images.githubusercontent.com/889881/144520085-5de375a1-2533-4c80-b9e1-fa02ed40d732.png)

In the tab for the Bluetooth half of the device, the Share button corresponds to Button 12 and can successfully be bound.

AntiMicroX, on the other hand, instead displays these controllers as one device with 21 buttons for some reason:

![amx](https://user-images.githubusercontent.com/889881/144520351-da1e2b02-b997-4ebe-8371-6d6e9b6e8615.png)

This would be preferable if one of those extra six buttons corresponded to the Share button. Unfortunately, that's not the case. There's just six extra buttons there, for no reason, that don't actually exist on the controller, and I can no longer bind the Share button at all. Can this behavior be improved?

**Comment by pktiuk** [comment] 2021-12-03 09:08
Please use bug template for this kind of issues.

**Comment by pktiuk** [comment] 2022-01-10 14:37
Could you provide some logs? https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs

Just turn on (and off after some time) AntiMicroX with this controller connected. I would like to check report generated about this device.

**Comment by blackwind** [comment] 2022-01-10 22:15
Problem still occurs.

[AntiMicroX.log](https://github.com/AntiMicroX/antimicrox/files/7842202/AntiMicroX.log)

**Comment by pktiuk** [comment] 2022-01-10 22:38
What is your system? Windows 10/11?

**Comment by blackwind** [comment] 2022-01-10 22:57
Windows 10 21H2

**Comment by I-g-e** [comment] 2022-01-11 09:38
The problem occurs on Linux (Fedora) as well, on the latest release. I can also post a log if needed.

**Comment by pktiuk** [comment] 2022-01-11 12:09
@I-g-e   
It would be helpful.  
Could you also check this gamepad with other apps like `qjoypad` or `jstest-gtx` (to check if gamepad is source of problems)?   
It would be good to check whether app [SDL gamepad tool](https://generalarcade.com/gamepadtool/) recognizes pressing this button (to check if this problem is caused by SDL).

**Comment by pktiuk** [comment] 2022-01-14 18:54
@blackwind   
Could you also check your gamepad with [SDL gamepad tool ](https://generalarcade.com/gamepadtool/)?

**Comment by I-g-e** [comment] 2022-01-14 21:16
Here’s my log: [antimicrox.log](https://github.com/AntiMicroX/antimicrox/files/7873038/antimicrox.log)

This is from the Flatpak version. I realized the maintained package on my distro (Fedora) is actually one version behind (3.2.0).

Unfortunately I didn’t get QJoyPad working. Compiled without problems, but there isn’t any kind of response when opening the program (no GUI, no logs, no anything). Jstest-gtx recognized every button and axis _except_ for the share button.

SDL2 Gamepad Tool does recognize the button press when I map it to some other button, but that means one other button cannot be mapped at all, since the program expects only the amount of mappings you’d have on previous Xbox controller iterations (same with AntiMicroX’s mapping dialog).

**Comment by pktiuk** [comment] 2022-01-15 16:16
I think this issue may be caused by SDL2.  
It seems to still have some bugs linked with share button on this gamepad   
 https://github.com/libsdl-org/SDL/issues?q=is%3Aissue+Xbox+Series+X+share+is%3Aopen+

**Comment by I-g-e** [comment] 2022-01-15 18:59
That seems to be the case. I compiled their test programs and used the provided `testgamepad` command. When pressing the share button, it gives this output:

> The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 175 (167), X11 KeySym 0x1008FF1C (XF86AudioRecord).

I’ll try posting some info on one of those threads.

**Comment by pktiuk** [comment] 2022-02-28 19:57
Closing, because this issue is out of scope of AntiMicroX.    
This issue should be fixed on SDL2 side.

**Comment by Igetin** [comment] 2022-09-28 19:45
@pktiuk Can you reopen this issue? SDL **does**, in fact, support the share button of the controller. The "not recognized by SDL" error message was a red herring, which is caused by the Linux kernel driver translating the share button press into a (non-joypad) key press, resulting in SDL showing *both* the button press *and* the error for the unrecognized key press.

AntiMicroX's log output was also lacking because of the kernel driver not directly supporting the button.

As discovered [here](https://github.com/libsdl-org/SDL/issues/6296), AntiMicroX does not recognize the share button because it is not handling the [`SDL_CONTROLLER_BUTTON_MISC1` button type](https://wiki.libsdl.org/SDL_GameControllerButton).

The SDL mapping string looks like this when created with their mapping tool:

```
050000005e040000130b000007050000,Xbox Series X Controller,platform:Linux,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,misc1:b15,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:+a4,
```

The `misc1:b15` part there is the mapping for `SDL_CONTROLLER_BUTTON_MISC1`.

---

Another closely related thing: I think the controller mapping dialog of AntiMicroX should be updated to support this additional button as well. The button should be shown in the mapping list and in the controller image.

Here is how SDL's official mapping tool displays it:
<img src="https://user-images.githubusercontent.com/14016863/192866293-b8ec8941-5162-4f02-83c0-b474bed1447e.png" width=340>

Of course, I can make this into a separate issue, if needed.

**Comment by pktiuk** [comment] 2022-10-10 15:19
@Igetin  

```
# of Buttons:    15
```

This value is obtained with SDL API [SDL_JoystickNumButtons()](https://wiki.libsdl.org/SDL_JoystickNumButtons).    

Are you sure the `Share` button is missing? Can you map/activate all of the 15 reported buttons? (If not a screenshot would be handy)   

If we are sure that Button linked with Sharing is missing then we can be sure, that SDL doesn't report number of buttons correctly.   
If there is a button you can't assign, then I will have to investigate filtering events inside of `InputDaemon`.

--------------

In terms of the first report https://github.com/AntiMicroX/antimicrox/issues/307#issue-1070082847 (about 21 buttons)    
It appears, that a number of buttons was hardcoded for gamepads. It will be fixed in https://github.com/AntiMicroX/antimicrox/pull/555

**Comment by Igetin** [comment] 2022-10-10 20:43
> Are you sure the `Share` button is missing? Can you map/activate all of the 15 reported buttons? (If not a screenshot would be handy)

I tried now with the latest version of AntiMicroX available on my distro (Fedora), which is 3.2.4, and also with the latest Flatpak release, which is 3.2.5. My results were the same for both.

The reported button number is actually different from the log I posted in January (which was running on version 3.2.1). Now the number is 21, which matches the different issue you mentioned and that was apparent in the OP:

<details>
<summary>Show log</summary>

```
[22:48:32.454] 🟢INFO	Created new GameController:
			Index:            1
			  UniqueID:         050000005e040000130b00000705000011182835
			  GUID:             050000005e040000130b000007050000
			  VendorID:         1118
			  ProductID:        2835
			  Product Version:  1287
			  Name:             Xbox Series X Controller
			  Game Controller: Yes
			  # of Axes:       6
			  # of Buttons:    21
			  # of Hats:       0
```
</details>

To reiterate, my actual controller has exactly 16 buttons (all of which are visible in the image posted by the OP).

Despite the different (and still incorrect) amount of buttons reported, I still cannot map the share button. Nothing is highlighted in the GUI and nothing is printed in the logs when I press the button. Here's me pressing all of my buttons:

<details>
<summary>Show log</summary>

```
[22:49:20.408] 🐞DEBUG	Processing joyEvent for: A: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:20.419] 🐞DEBUG	Processing joyEvent for: A: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:21.649] 🐞DEBUG	Processing joyEvent for: B: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:21.720] 🐞DEBUG	Processing joyEvent for: B: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:22.981] 🐞DEBUG	Processing joyEvent for: Y: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:23.042] 🐞DEBUG	Processing joyEvent for: Y: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:23.613] 🐞DEBUG	Processing joyEvent for: X: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:23.684] 🐞DEBUG	Processing joyEvent for: X: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:24.615] 🐞DEBUG	Processing joyEvent for: R Shoulder: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:24.716] 🐞DEBUG	Processing joyEvent for: R Shoulder: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:25.317] 🐞DEBUG	Processing joyEvent for: L Shoulder: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:25.429] 🐞DEBUG	Processing joyEvent for: L Shoulder: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:33.694] 🐞DEBUG	Processing joyEvent for: LS Click: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:33.867] 🐞DEBUG	Processing joyEvent for: LS Click: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:37.996] 🐞DEBUG	Processing joyEvent for: RS Click: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:38.188] 🐞DEBUG	Processing joyEvent for: RS Click: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:39.964] 🐞DEBUG	Processing joyEvent for: DPad - Button Left: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:40.045] 🐞DEBUG	Processing joyEvent for: DPad - Button Left: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:40.436] 🐞DEBUG	Processing joyEvent for: DPad - Button Up: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:40.547] 🐞DEBUG	Processing joyEvent for: DPad - Button Up: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:40.949] 🐞DEBUG	Processing joyEvent for: DPad - Button Right: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:41.070] 🐞DEBUG	Processing joyEvent for: DPad - Button Right: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:41.440] 🐞DEBUG	Processing joyEvent for: DPad - Button Down: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:41.562] 🐞DEBUG	Processing joyEvent for: DPad - Button Down: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:43.723] 🐞DEBUG	Processing joyEvent for: Back: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:43.844] 🐞DEBUG	Processing joyEvent for: Back: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:44.325] 🐞DEBUG	Processing joyEvent for: Guide: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:44.576] 🐞DEBUG	Processing joyEvent for: Guide: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:45.537] 🐞DEBUG	Processing joyEvent for: Start: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
[22:49:45.678] 🐞DEBUG	Processing joyEvent for: Start: [NO KEY] (file ir/build/BUILD/antimicrox-3.2.4/src/joybutton.cpp:174)
```
</details>

And here's a screenshot of the GUI:

<details>
<summary>Show screenshot</summary>

![Screenshot from 2022-10-10 23-12-43](https://user-images.githubusercontent.com/14016863/194945248-183e9da2-621b-454f-bd0e-b87ae7b8ecc2.png)
</details>

I did try to map all the shown extra buttons just in case, but none of those buttons 16–21 seem to be the share button since the mapped key is not inputted when I press the button.

> This value is obtained with SDL API [SDL_JoystickNumButtons()](https://wiki.libsdl.org/SDL_JoystickNumButtons).
> 
> If we are sure that Button linked with Sharing is missing then we can be sure, that SDL doesn't report number of buttons correctly.
> If there is a button you can't assign, then I will have to investigate filtering events inside of InputDaemon.

I don't think the number thing is a problem with SDL (at least anymore?). I again compiled the latest version of their [test mapper](https://github.com/libsdl-org/SDL/blob/main/test/controllermap.c), and it shows the correct number of buttons:

<details>
<summary>Show log</summary>

```
INFO: There are 1 joysticks attached
INFO: Joystick 0: Xbox Series X Controller
INFO:        axes: 6
INFO:       balls: 0
INFO:        hats: 1
INFO:     buttons: 16
INFO: instance id: 0
INFO:        guid: 050000005e040000130b000007050000
INFO:     VID/PID: 0x045e/0x0b13
INFO: Watching joystick 0: (Xbox Series X Controller)
INFO: Joystick has 6 axes, 1 hats, 0 balls, and 16 buttons
```
</details>

It is also [using the exact API](https://github.com/libsdl-org/SDL/blob/6784d84c9dec5177b26f71ea6cd7ebb396a195af/test/controllermap.c#L380) you mentioned. Is AntiMicroX maybe using a too old version of SDL or something?

**Comment by pktiuk** [comment] 2022-10-10 22:40
@Igetin   
You can download build with fix showing proper number of buttons here: https://github.com/pktiuk/antimicrox/releases/tag/3.2.5-withfixes (but you may wait 10-20 minutes until binaries will appear there).

Do you have `Button 16: [NO KEY]` in updated app?

> It is also [using the exact API](https://github.com/libsdl-org/SDL/blob/6784d84c9dec5177b26f71ea6cd7ebb396a195af/test/controllermap.c#L380) you mentioned. Is AntiMicroX maybe using a too old version of SDL or something?

This is possible. (you can check used SDL version in logs and in `Help->About` window)

**Comment by Igetin** [comment] 2022-10-12 19:17
> Do you have Button 16: [NO KEY] in updated app?

Yeah, the button count is now correct with that build. :+1:

**Comment by pktiuk** [comment] 2022-10-13 19:22
> > Do you have Button 16: [NO KEY] in updated app?
> 
> Yeah, the button count is now correct with that build. +1

Have you checked all the buttons on the gamepad? Are you sure that none of them activates `Button 16: [NO KEY]`?

I added some new logs which could help with dealing with this issue. Build with these changes is here:
https://github.com/pktiuk/antimicrox/releases/tag/3.2.5-new-logs


Could you collect some logs for me? Just open an app and press `Share` button 5 times (having exact 5 press would ensure me that I am looking at good event :) ) , then press another button like `A` once and close an app.

**Comment by Igetin** [comment] 2022-10-16 12:30
Sorry, it took me some time to get back to this.

> Have you checked all the buttons on the gamepad? Are you sure that none of them activates Button 16: [NO KEY]?

Yes, none of them activates that one.

> Could you collect some logs for me? Just open an app and press Share button 5 times (having exact 5 press would ensure me that I am looking at good event :) ) , then press another button like A once and close an app.

Here is the full log: [antimicrox_3.2.5-new-logs_button_test_2022-10-16.log](https://github.com/AntiMicroX/antimicrox/files/9794439/antimicrox_3.2.5-new-logs_button_test_2022-10-16.log). I used the AppImage build.

It appears that the share button press generates events of the type `SDL_JOYBUTTONUP` and `SDL_JOYBUTTONDOWN`, but **not** `SDL_CONTROLLERBUTTONDOWN` and `SDL_CONTROLLERBUTTONUP` (unlike other buttons).

**Comment by pktiuk** [comment] 2022-10-16 12:41
```
[15:12:59.623] 🐞DEBUG	Processing event: SDL_CONTROLLERBUTTONUP From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.623] 🐞DEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 0 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:12:59.623] 🐞DEBUG	Processing JoyButton::joyEvent for: A: [NO KEY] SDL index: 0 className: JoyButton (file unner/work/antimicrox/antimicrox/src/joybutton.cpp:179)
[15:13:02.394] 🐞DEBUG	Processing event: SDL_JOYBUTTONDOWN From joystick with instance id: 0 Got button with id: 15 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
[15:13:02.544] 🐞DEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 15 is one of the GameControllers: true is one of the joysticks:false (file unner/work/antimicrox/antimicrox/src/inputdaemon.cpp:751)
```
I think we just figured out source of this problem.

**Comment by Igetin** [comment] 2022-10-16 16:18
So, since the missing mapping [is now included in SDL](https://github.com/libsdl-org/SDL/commit/70dfd6dd1a89f753c47bf5db06fa843a60af5169), it would seem like this problem should be fixed when SDL 2.26.0 is released ([due by November 01, 2022](https://github.com/libsdl-org/SDL/milestone/7)), and after a new release of AntiMicroX is built against the new SDL release.

I also noticed that AntiMicroX includes a copy of SDL_GameControllerDB. Should that be updated as well?

**Comment by pktiuk** [comment] 2022-10-16 17:25
> I also noticed that AntiMicroX includes a copy of SDL_GameControllerDB. Should that be updated as well?   

Yes.   
The source of our SDL_GameControllerDB is https://github.com/gabomdq/SDL_GameControllerDB   
It is possible, that this mapping should be also fixed in there.

**Comment by Igetin** [comment] 2022-10-16 18:09
I fixed the mapping on the DB a few days ago! What I meant is that AntiMicroX should probably update its local copy since it was last updated 10 months ago. :P

**Comment by pktiuk** [comment] 2022-10-16 18:13
I will do it now, anyway I should do it from time to time :)

**Closed** 2022-10-16 18:30 UTC
Labels: bug

**Comment by pktiuk** [comment] 2022-10-16 18:48
I think you could just test this fix now by swapping file `/usr/share/antimicrox/gamecontrollerdb.txt` with the latest file [from repository](https://github.com/AntiMicroX/antimicrox/blob/master/share/gamecontrollerdb_linux.txt)

**Comment by Igetin** [comment] 2022-10-17 22:02
Yes, that did indeed immediately make the button work. Although I noticed a weird quirk with it: for some reason, if I map a key to the share button, the event will fire _noticably slower_ than for all the other buttons. I snagged a quick clip of it in action:

https://user-images.githubusercontent.com/14016863/196291134-c717abcb-b581-492c-8ae4-7146f0d659a5.mp4

As it is now, I wouldn't really map it to any action that requires an instant response. It's several hundred milliseconds slower than the other buttons.

The lag **only** happens when I've mapped a key to the button. When nothing is mapped, the events fire at the same normal speed as with the other buttons. I tried the `showkey` program as well (shown on the video), which also shows the additional lag for the button *if* it is mapped in AntiMicroX. I don't really have any idea what might be causing that…

**Comment by shogunreaper** [comment] 2022-11-27 14:35
has anyone been able to get this to work on windows 10?

**Comment by pktiuk** [comment] 2022-11-29 11:03
@Igetin Could you create separate issue for this problem? It seems to be a really tricky problem.

**Comment by pktiuk** [comment] 2022-11-29 15:03
If it does not happen anymore, then no (maybe they just fixed it in SDL)

**Comment by blackwind** [comment] 2023-10-29 09:20
Still unable to map the Share button here with v3.3.4-with-SDL2.28.2. Does anyone have any pointers?

**Comment by derinsh** [comment] 2024-01-30 22:24
This seems to be a really strange issue. I am running Windows and recently got a new Series X controller.

The Share button is identified as b11, and I can successfully map it. The problem is AntimicroX doesn’t let me map an extra button for the controller. So I have to replace another mapping.

For example, I could map the Share button (b11) to Guide, but now I couldn’t bind my Guide button to anything since it’s unmapped.

I tried manually opening antimicrox_settings and adding misc1:b11 to my mapping string. Now my Share button works and functions as Button 16 in the GUI.

I logged pressing the button and here is an excerpt:

```
[23:19:40.387] 🐞DEBUG	Processing event: SDL_JOYBUTTONDOWN From joystick with instance id: 0 Got button with id: 11 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[23:19:40.387] 🐞DEBUG	Processing JoyButton::joyEvent for: Button 16: [NO KEY] SDL index: 15 className: JoyButton (file /src/joybuttontypes/joybutton.cpp:179)
[23:19:40.387] 🐞DEBUG	"Processing press for button #1 - Button 16"
[23:19:40.387] 🐞DEBUG	Added button  "Button 16"  to list
[23:19:40.387] 🐞DEBUG	List has  1  buttons
[23:19:40.507] 🐞DEBUG	Processing event: SDL_CONTROLLERBUTTONUP From joystick with instance id: 0 Got button with id: 15 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Controller has  6  raw axes
[23:19:40.507] 🐞DEBUG	Processing event: SDL_JOYBUTTONUP From joystick with instance id: 0 Got button with id: 11 is one of the GameControllers: true is one of the joysticks:false (file /src/inputdaemon.cpp:738)
[23:19:40.507] 🐞DEBUG	Processing JoyButton::joyEvent for: Button 16: [NO KEY] SDL index: 15 className: JoyButton (file /src/joybuttontypes/joybutton.cpp:179)
[23:19:40.507] 🐞DEBUG	"Processing release for button #1 - Button 16"
[23:19:40.507] 🐞DEBUG	There is end of slotiter. Set currentCycle and previousCycle as null pointers
```

**Comment by pktiuk** [comment] 2024-10-22 19:01
Are you able to map this button using tools mentioned in this repository? : https://github.com/mdqinc/SDL_GameControllerDB 

If not, then you should report it directly to SDL
