### ISSUE TITLE
Map keys to fictional controller instead of keyboard

### ISSUE THREAD

**Issue by denizterek** [AntiMicroX/antimicrox#1081] opened 2024-11-13 19:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I'm currently using AntiMicroX so I can hot-swap steering wheels on my racing simulator. All my steering wheel buttons are remapped to keyboard input and the games read keyboard input for functions such as upshifting and downshifting. I no longer need to relaunch games whenever I want to use another steering wheel, but if anything touches the keyboard, the game will take all those inputs.

### Describe the solution you'd like

If we could map controller inputs to a new controller that's created by AntiMicroX, it would allow for all the same hot-swapping advantages while also eliminating the possibility of misinputs from the keyboard.

### Additional context

There would be no need for any linear inputs, just simple buttons on a fictional controller/button box would more than solve this issue.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1081">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1081/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1081/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment] 2024-11-13 21:54
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/65 

Direct answer: https://github.com/AntiMicroX/antimicrox/issues/65#issuecomment-1214160681

**Closed by pktiuk** 2024-11-13 21:54 UTC
Labels: enhancement
