### ISSUE TITLE
Moving button assignments between sets

### ISSUE THREAD

**Issue by SarahSzabo** [AntiMicroX/antimicrox#778] opened 2023-04-28 21:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It would be useful if you realize that 2 buttons on the same set are better off on each other's buttons.

### Describe the solution you'd like

Right click button on mapping screen -> 

"Swap With" menu tree -> 
"Set 1, Set 2, ..." (Options) -> 
Set 1 -> 
Button 1, Button 2 (Options) ->
Button 5

Button 20 and 5 swapped notification on system.

**Comment by pktiuk** [comment] 2023-06-09 22:16
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/764

**Closed by pktiuk** 2023-06-09 22:16 UTC
Labels: duplicate, enhancement
