### ISSUE TITLE
Controller with motion sensing to xinput controller mapping

### ISSUE THREAD

**Issue by dnikic** [AntiMicroX/antimicrox#1099] opened 2024-11-24 22:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

This feature would aim to provide the following functionalities:
Users of controllers with advanced sensors  to utilize them in games and platforms that support only xinput.
Provide a functionality commonly used in Steam input tools.

Example usage case:
GeForceNow does not support the gyro functionality, but if I could use AntimicroX to present my DualShock 4 controllers motion sensing as right stick inputs on an xinput controller I would be able to utilize the gyro motion sensing as a right stick. 

### Describe the solution you'd like

The current "Controller Mapping" section does not support newer sensors such as motion sensors and a track pad. The best approach may be, instead of extending it, to add an additional controller card  alongside keyboard and mouse, when setting a buttons functionality.

![Screenshot from 2024-11-24 23-40-10](https://github.com/user-attachments/assets/eb1fd8fc-e7a2-433d-98de-cac3772c44f7)

### Describe alternatives you've considered

Why not map everything to the keyboard? 
Because some games have better controller support than keyboard and mouse support.

Why not use the motion sensing as a mouse, and the rest of the controller as a controller?
Some games do not support both inputs simultaneously or keep flashing messages upon changing the input method. 

### Additional context

I hope this feedback is useful for the amazing devs of this project. 
If some assistance from my side is needed feel free to contact me.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1099">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1099/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1099/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment] 2024-11-24 23:53
Duplicate of: https://github.com/AntiMicroX/antimicrox/issues/65

**Closed by pktiuk** 2024-11-24 23:53 UTC
Labels: enhancement
