### ISSUE TITLE
Stopped detecting controllers after Manjaro update.

### ISSUE THREAD

**Issue by Git-Forked** [AntiMicroX/antimicrox#450] opened 2022-05-18 12:22 UTC
Manjaro as a rolling release updates often, and in large chunks.  I did remember seeing some updates pertaining to joysticks.  I looked for the update log to show which files they were, but I could not find a log file. 
Previous to this update AntiMicroX was detecting my XBOX controller.  After the update there is no controller detection, even when refreshing multiple times.

**Comment by Git-Forked** [comment] 2022-05-19 15:09
My apologies. 
Deleting and rebuilding solved the issue.

**Comment by Git-Forked** [comment] 2022-05-23 00:17
Apparently rebuilding only solved the issue until a reboot, then the issue reappears.  I would hope I don't have to rebuild every time the computer boots.  Perhaps there is something in the code that can be updated to overcome this.  Thank you.

**Comment by pktiuk** [comment] 2022-07-20 19:10
### Please follow our issue templates when reporting bugs or requesting features.

Following the template also provides us all the information we need, without having to ask for it.

This problem is probably caused by the latest SDL or other driver in kernel. This seems to be out of scope.

**Closed by pktiuk** 2022-07-20 19:10 UTC
