### ISSUE TITLE
Execute file assinement slot not doing anything.

### ISSUE THREAD

**Issue by SolidSouless** [AntiMicroX/antimicrox#349] opened 2022-01-23 02:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Advanced assignments, I added "Execute program when slot is activated" and selected my exe. However when the button is pressed on the controller nothing happens.

### Steps To Reproduce

1. Click on Button I'm trying to assign execute file assignment  
2. Go to advanced.
3. Select Execute, and choose my exe file, insert slot and exit.
4. Button now says [Exec] "program.exe".
5. Press button on controller and nothing happens.

### Environment

```markdown
- OS:Windows
- AntiMicroX version:3.2.1
```

**Comment by mattdsteele** [comment] 2022-01-30 19:41
I'm seeing a similar behavior (Windows 11, version 3.2.1). As an example, and a few screenshots of my configuration:

![image](https://user-images.githubusercontent.com/389077/151714780-81a00680-ec8f-4724-b75c-0256dc6b8882.png)
![image](https://user-images.githubusercontent.com/389077/151714790-76447d2f-1e5b-41dd-bbb3-ce1cd5cafc45.png)
![image](https://user-images.githubusercontent.com/389077/151714800-f97700cc-6e3a-4ca7-9e03-4030f2dbce96.png)

Standard keyboard mappings appear to work fine. Let me know if there's any other details I could provide, thanks!

**Comment by pktiuk** [comment] 2022-02-02 13:51
Could you collect some logs from this issue?  
https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs

**Comment by mattdsteele** [comment] 2022-02-02 19:29
I've attached logs at a debug level. In this log, I launch AntiMicroX, press L Stick `left` three times, then `B` and `A`, then L Stick `left` again

[controller-logs.log](https://github.com/AntiMicroX/antimicrox/files/7989473/controller-logs.log)
.

**Comment by pktiuk** [comment] 2022-02-03 22:11
```
[13:27:32.251] ??INFO	Executing command:  " C:/Windows/System32/cmd.exe "
[13:27:32.278] ??DEBUG	Active slots are: 
```

I expected `Command cannot be executed`

Process seems to start successfully, but it fails later.  
I will have to add improve program execution to track what happens with launched programs. (or at least [define their outputs](https://www.qt.io/blog/2017/08/25/a-new-qprocessstartdetached))

**Comment by pktiuk** [comment] 2022-02-12 22:47
I think it could be caused by wrong working directory of executable.  
Now AntiMicroX tries to launch `cmd.exe` in location of `antimicrox.exe` instead of location where `cmd.exe` is stored.  

It should be fixed by: https://github.com/AntiMicroX/antimicrox/pull/377  
In my case it fixed launching firefox

**Comment by mattdsteele** [comment] 2022-02-12 23:11
Thank you for investigating!

If you think you’ll be packaging up a new release soon I can test it out then; I don’t think I have all the build tools to compile for Windows.

**Comment by pktiuk** [comment] 2022-02-28 19:48
@mattdsteele   @SolidSouless 

Could you tell me how does it work with the latest release? `3.2.2.`

**Comment by SolidSouless** [comment] 2022-02-28 22:27
@pktiuk 

It seems to work now with 3.2.2. Thanks :)

**Closed** 2022-02-28 22:30 UTC
Labels: bug, waiting for feedback

**Comment by mattdsteele** [comment] 2022-03-01 00:55
I can also confirm that with 3.2.2 I can launch applications successfully.

Strangely, when I try to execute `cmd.exe` I do not see a terminal window open, but looking at the logs I can verify it's successful and has a PID associated. I am able to successfully launch other apps, such as `explorer.exe`, so this is mostly just noting for posterity.

Thanks again!
