### ISSUE TITLE
Tests fail to compile

### ISSUE THREAD

**Issue by xgqt** [AntiMicroX/antimicrox#530] opened 2022-09-01 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
In file included from /tmp/tmp.3DQ37MtJq4/antimicrox/tests/testaboutdialog.cpp:20:
/tmp/tmp.3DQ37MtJq4/antimicrox/src/gui/aboutdialog.h:22:10: fatal error: QDialog: No such file or directory
   22 | #include <QDialog>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [tests/CMakeFiles/GuiTests.dir/build.make:90: tests/CMakeFiles/GuiTests.dir/testaboutdialog.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:311: tests/CMakeFiles/GuiTests.dir/all] Error 2
```

### Expected Behavior

Tests compile.

### Steps To Reproduce

Build with `-DWITH_TESTS=ON`: `cmake -DWITH_TESTS=ON && make -j1`.

The project does buid & run without `-DWITH_TESTS=ON`. 
My guess is that test dir's CMakeLists.txt is messed up somewhere.

### Environment

```markdown
- OS: GNU/Linux, Gentoo
- AntiMicroX version: git HEAD
```

**Comment by pktiuk** [comment] 2022-09-08 12:53
It is duplicate of https://github.com/AntiMicroX/antimicrox/issues/138  
Tests do not compile because they have never been finished

**Closed by pktiuk** 2022-09-08 12:53 UTC
Labels: bug, duplicate
