### ISSUE TITLE
Auto profile is not working properly

### ISSUE THREAD

**Issue by ds47x** [AntiMicroX/antimicrox#387] opened 2022-02-24 14:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I used 2 profiles in auto profile setting it just disappear like I didnt save it, I searched many websites but there is nothing....if this issue is fixed tell me but if it isnt please see it

### Environment

```markdown
- OS:window
- AntiMicroX version:3.2.1
```

**Comment by ds47x** [comment] 2022-02-25 07:37
Still didnt work in version 3.2.2

**Comment by nxtsem** [comment] 2022-03-03 20:16
I see the same issue.  Seems to still work with antimicro 2.23

**Comment by ds47x** [comment] 2022-03-04 04:14
> I see the same issue.  Seems to still work with antimicro 2.23

Thanks bro

**Comment by Xasin** [comment] 2022-03-06 09:01
To me it appears that I can't even create Auto Profiles.
I can open the dialogue to create a new profile just fine, and I can select the profile to use as well as the window properties to be used...

But upon clicking "OK", no extra entry has been added to the list of auto profiles.

Using:
AntiMicroX 3.2.2 (installed via FlatHub)
Stock Debian 11
Saitek Pro Gamer Command Unit

**Comment by joaoasilva** [comment] 2022-03-15 18:19
I have exactly the same issue

> To me it appears that I can't even create Auto Profiles. I can open the dialogue to create a new profile just fine, and I can select the profile to use as well as the window properties to be used...
> 
> But upon clicking "OK", no extra entry has been added to the list of auto profiles.
> 
> Using: AntiMicroX 3.2.2 (installed via FlatHub) Stock Debian 11 Saitek Pro Gamer Command Unit

**Comment by pktiuk** [comment] 2022-04-14 19:21
Closing, because this seems to be a duplicate of https://github.com/AntiMicroX/antimicrox/issues/252

For now workaround is defining any path, saving and later removing it.

I will investigate it.

**Closed by pktiuk** 2022-04-14 19:21 UTC
Labels: bug
