### ISSUE TITLE
AntiMicroX system tray icon not appearing in flatpak package

### ISSUE THREAD

**Issue by tawfeqfauzi** [AntiMicroX/antimicrox#58] opened 2020-10-03 13:04 UTC
**Describe the bug**
Upon opening, the app doesn't display the system tray icon.

**Screenshots**
![03 ⁄ 10 ⁄ 2020 20-58](https://user-images.githubusercontent.com/68013133/94992272-7b43db80-05bb-11eb-90b9-235a4db88776.png)

**Version**
Running version 3.1.2
Distro is 20.04 LTS Pop! OS 64-bit with Gnome 3.36.3 as my DE

**Additional context**
On debugging I noticed something, and I'll also attach the full log:
Line 42 Warning: failed to register service "org.kde.StatusNotifierItem-2-1" ((null):0, (null))
[debug antimicrox.zip](https://github.com/AntiMicroX/antimicrox/files/5321680/debug.antimicrox.zip)

**Comment by pktiuk** [comment] 2020-10-03 16:34
Do you use flatpak package?

**Comment by gombosg** [comment] 2020-10-03 17:14
Thanks for reporting!
This might be the same as #55 .

Try this extension for GNOME: extensions.gnome.org/extension/1503/tray-icons
Or this: https://extensions.gnome.org/extension/1031/topicons/

I tried and it works with both, with Flatpak and with native app, too.

If it works for you, I'll add this to the README.
If not, I'll spin up a POP! VM, but I'd appreciate if you could test. :slightly_smiling_face:

**Comment by pktiuk** [comment] 2020-10-03 17:41
@gombosg 
I have already installed POP! OS on VM, I will check, when I will get to know which version was used.

**Comment by tawfeqfauzi** [comment] 2020-10-03 18:42
> Do you use flatpak package?

Yes flatpak 3.1.2

**Comment by tawfeqfauzi** [comment] 2020-10-03 18:44
> Thanks for reporting!
> This might be the same as #55 .
> 
> Try this extension for GNOME: https://extensions.gnome.org/extension/1503/tray-icons
> Or this: https://extensions.gnome.org/extension/1031/topicons/
> 
> I tried and it works with both, with Flatpak and with native app, too.
> 
> If it works for you, I'll add this to the README.
> If not, I'll spin up a POP! VM, but I'd appreciate if you could test. slightly_smiling_face

I've tried both extensions and unfortunately both don't resolve the issue

**Comment by tawfeqfauzi** [comment] 2020-10-03 18:47
``Gtk-Message: 02:45:29.013: Failed to load module "appmenu-gtk-module"
Gtk-Message: 02:45:29.080: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:45:29.080: Failed to load module "canberra-gtk-module"
Warning: failed to register service "org.kde.StatusNotifierItem-2-1" ((null):0, (null))``

These 4 lines keep appearing every time I run the app through terminal

**Comment by tawfeqfauzi** [comment] 2020-10-03 18:47
Gtk-Message: 02:45:29.013: Failed to load module "appmenu-gtk-module"
Gtk-Message: 02:45:29.080: Failed to load module "canberra-gtk-module"
Gtk-Message: 02:45:29.080: Failed to load module "canberra-gtk-module"
Warning: failed to register service "org.kde.StatusNotifierItem-2-1" ((null):0, (null))

These 4 lines keep appearing every time I try to run it through terminal

**Comment by pktiuk** [comment] 2020-10-03 20:13
@gombosg 
This is flatpak issue.
On Pop OS everything works correctlu witd `deb` package, but flatpak has problem with icon.

**Comment by pktiuk** [comment] 2020-10-03 21:47
The same problem with flatpak on Ubuntu 20.04.

**Comment by gombosg** [comment] 2020-10-04 08:41
Hm, confirmed - it works with older versions, I try to bisect the bug in this [testing branch](https://github.com/flathub/io.github.antimicrox.antimicrox/pull/3). (Needs to be tested with KDE, too)

**Comment by gombosg** [comment] 2020-10-04 20:36
Can you test [this build](https://github.com/flathub/io.github.antimicrox.antimicrox/pull/3#issuecomment-703295879)?
(After testing, you can remove it)

**Comment by pktiuk** [comment] 2020-10-04 21:19
Now it works for me.  
Does it work with kde?

**Comment by gombosg** [comment] 2020-10-05 07:17
If the ["Ubuntu Appindicators"](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension is on, then the menu will be like this:
![image](https://user-images.githubusercontent.com/23086060/95049453-14711000-06ea-11eb-8e8a-8f62df1ad734.png)

If it's off, and "Tray icons" extension is on, then it will be OK.

I tested in KDE and it looks like this:
![image](https://user-images.githubusercontent.com/23086060/95049997-1f787000-06eb-11eb-9a0c-b13b6182be95.png)

Similar to the above, without the "x"-es.
For comparison, it's supposed to look like this:
![image](https://user-images.githubusercontent.com/23086060/95050273-8dbd3280-06eb-11eb-98ed-6b27c1a34c2d.png)

Here, we need to look into the code to see how it interacts with various tray icon protocols.

**Comment by pktiuk** [comment] 2020-10-05 11:32
I will further investigate it.

**Comment by tawfeqfauzi** [comment] 2020-10-06 13:25
I found this in the Flatpak documentation:

> Status icons are the same concept as the system tray or the taskbar on Windows, or menu bar icons on Mac. These are supported on most Linux distributions, through libappindicator.
> 
> A number of Linux distributions don’t show status icons. It is still possible to provide a status icon, and it will be shown in some distributions. However, in order to ensure compatibility, it is recommended to only use status icons in a supplementary manner, and not to rely on them as the only mechanism for providing status information or access to particular features. This includes “minimize to tray” (or equivalent) functionality.
> 
> XEmbed style icons will function with the x11 permission but all other status icon interfaces require extra permissions to escape the sandbox and these services are not designed to be robust against untrusted software.

Here's a link too: https://docs.flatpak.org/en/latest/desktop-integration.html#status-icons

**Comment by gombosg** [comment] 2020-10-06 20:16
Thanks! I merged a flatpak quick fix (try updating) until we get a better view of the issue.

**Closed** 2020-10-13 09:07 UTC
Labels: bug, packaging
