### ISSUE TITLE
antimicrox don't work like keyboard

### ISSUE THREAD

**Issue by ETime-Github** [AntiMicroX/antimicrox#723] opened 2023-02-08 14:30 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

This is keyboard.
![keyboard](https://user-images.githubusercontent.com/116369640/217558623-a7fd3f3e-f3e0-44cc-911b-092490bec254.gif)

This is antimicro. Turbo off.
![antimicro](https://user-images.githubusercontent.com/116369640/217558672-6beb0415-b059-440c-82ad-08a48af1a7be.gif)

This is antimicroX. Turbo off.
![antimicrox](https://user-images.githubusercontent.com/116369640/217558715-008ff7d1-8727-4f53-84cb-20ed76da4965.gif)

This is antimicroX. Turbo on.
![antimicroxtubro](https://user-images.githubusercontent.com/116369640/217558767-f77e31ea-b7d0-4966-8ffc-f07ad3cc2831.gif)

---
Using keyboard in the game, if I hold down the arrow keys and "do something"key, the character will keep walking and do something, do something, do something...

Using antimicro (Turbo off) in the game, just like using keyboard.

Using antimicroX (Turbo off) in the game, the character will keep walking and do something once.

Using antimicroX (Turbo on) in the game, the character will walk and do something, walk and do something, walk and do something... like game lagging.

### Expected Behavior

antimicroX should work like keyboard.

### Environment

```markdown
antimicro 2.24
antimicroX 3.3.3
Windows 22H2
```

**Comment by ETime-Github** [comment] 2023-02-12 02:20
I found the difference between antimicro and antimicroX, it's in the options, but antimicroX can't  enabled.
![GIF 2023-02-12 10-15-58](https://user-images.githubusercontent.com/116369640/218289409-87c4e48a-5cab-46ba-8603-f78bf88aec5c.gif)

**Comment by pktiuk** [comment] 2023-02-13 11:26
Check this issue: https://github.com/AntiMicroX/antimicrox/issues/115

**Comment by pktiuk** [comment] 2023-02-13 22:09
Duplicate of #115

**Closed by pktiuk** 2023-02-13 22:09 UTC
Labels: bug
