### ISSUE TITLE
a way to let the g29 wheel be seen as a controller

### ISSUE THREAD

**Issue by alidan** [AntiMicroX/antimicrox#1027] opened 2024-08-25 02:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

ill preface this with I may be dumb and just don't see this, I want to play a game that does not have any support for wheels at all, as far as I can tell in the logitech software there is no way for me to assign the wheel as the x axis of the left stick in that software, however in antimicrox I do have it set up as the x axis, 

![antimicrox_6vhJcS3s0H](https://github.com/user-attachments/assets/cacb9e71-c601-4121-af55-001e56906421)

there is a picture of me turning it a bit to show it does work, same with the break and throttle, 

break
![antimicrox_9teNyjSGds](https://github.com/user-attachments/assets/de1c4cc4-16f6-4317-9501-042d578bb301)

throttle
![antimicrox_KX9BDsZv6R](https://github.com/user-attachments/assets/05a58d9a-6ae1-4c95-a668-d64794cda07c)

what I want to do is have these mapped to a joystick and shoulder buttons, I was hoeing I would be able to do that, however I seem to have to map them to single button presses

### Describe the solution you'd like

I would like to map these to controller inputs to mimic a controller which is supported in games

### Describe alternatives you've considered

there is another program I have tried to use, but it completely took away any force feedback/centering spring and didn't have the controls inside of it to allow it to work correctly, it may be my error, well, its almost 100% my error setting that up.

### Additional context

for all other applications this works perfectly fine, but at least for me with wheel, because the wheel does not default to something like the left stick, and any button does not default to a controller button in games, its not seen as that in games. 

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1027">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1027/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1027/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment] 2024-11-24 14:02
Duplicate of: https://github.com/AntiMicroX/antimicrox/issues/65

**Closed by pktiuk** 2024-11-24 14:02 UTC
Labels: enhancement
