### ISSUE TITLE
AntiMicroX immediately removes the profile when a different app is in focus

### ISSUE THREAD

**Issue by Mapsking** [AntiMicroX/antimicrox#936] opened 2024-03-13 01:22 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Whenever I try to use AntimicroX, it will not keep the profile loaded. I upgraded to v.3.3.3, and also tried 3.3.4, and now 3.4.0, and it does the same thing. I noticed this happening when switching to other programs via ALT+TAB in Windows 10 x64, and also when minimizing the app. It also happens simply if a different app is in focus. When you select keybinds or a saved profile, and then switch to a different app or minimze it, the in use profile switches back to a blank profile, rendering the program useless.

Perhaps there is some setting I have accidentally set that prevents the controller profile actually being used?

The original Antimicro (v2.2.3) works correctly.

### Expected Behavior

I set buttons and keys according to my needs in AntiMicroX. I change to the game or application, and use my controller with the keybinds from AntiMicroX.

### Steps To Reproduce

1. Open AntiMicroX (Using v3.4.0).
2. Select Load <desired profile>.gamecontroller.amgp
3. Profile is loaded in the dropdown and shows <desired profile>.gamecontroller in the dropdown.
4. Open another app, such as Calculator.
5. Profile in dropdown immediately changes to <New>
6. Alternate method is selecting the profile directly from the dropdown instead of hitting the Load button.
7. The result is the same.
8. If a program (like Calculator) is already opened, and you then open a profile via the dropdown in AntiMicroX, and THEN switch to Calculator, the dropdown stays on <desired profile>.gamecontroller UNTIL you switch back to AntiMicroX, in which case it then reverts back to <New>.

### Environment

```markdown
Program Version 3.4.0
Compiled from packaging: GitHub Portable Windows Release
Built Against SDL 2.30.1
Running With SDL 2.30.1
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

Here is an example video of the problem. The original Antimicro (v2.2.3) works correctly.

https://youtu.be/hp_sLsVjoAg

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/936">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/936/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/936/pledge.svg">
</picture>
</a>

**Comment by mikehancoski** [comment] 2024-05-01 02:59
I have a very similar issue that unless antimicro is focused the inputs do not work  

The example above is the same except it does not blank the profile and you can just move to cursor out of the window and the inputs stop working in all apps 

and yes I have run it in as an administrator 

the issue was fixed by pausing my virus protection

**Comment by Mapsking** [comment] 2024-05-29 22:13
> I have a very similar issue that unless antimicro is focused the inputs do not work
> 
> The example above is the same except it does not blank the profile and you can just move to cursor out of the window and the inputs stop working in all apps
> 
> and yes I have run it in as an administrator
> 
> the issue was fixed by pausing my virus protection

I have also tried that, it seems to make no difference for me. Thanks for the suggestion.

**Comment by pktiuk** [comment] 2024-10-20 12:46
Could you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs) when this issue happens?

I need to check what triggers this change in your case. Maybe this may be linked with misbehaving autoprofile.

**Comment by Mapsking** [comment] 2024-11-06 13:10
Sure, here you go. I was not sure which log level to put it at, but based on the image linked, I had set it to debug. If you need a different one or need me to do anything specific for testing, please let me know. I opened AntimicroX, loaded a profile, moved the sticks randomly, switched to Calculator (already open), it removed the profile.

Thanks

**Comment by pktiuk** [comment] 2024-11-06 15:30
You did not post it.
Just drag and drop file into textbox

**Comment by Mapsking** [comment] 2024-11-08 05:03
> You did not post it. Just drag and drop file into textbox

I did that first, then I added it manually with the paper clip icon.
I will try again, maybe it will take this time.
[AntimicroX log.log](https://github.com/user-attachments/files/17673260/AntimicroX.log.log)

**Comment by itsnotlevel1** [comment] 2024-11-10 20:21
> ### Is there an existing issue for this?
> * [x]  I searched the existing issues and did not find anything similar.
> 
> ### Current Behavior
> Whenever I try to use AntimicroX, it will not keep the profile loaded. I upgraded to v.3.3.3, and also tried 3.3.4, and now 3.4.0, and it does the same thing. I noticed this happening when switching to other programs via ALT+TAB in Windows 10 x64, and also when minimizing the app. It also happens simply if a different app is in focus. When you select keybinds or a saved profile, and then switch to a different app or minimze it, the in use profile switches back to a blank profile, rendering the program useless.
> 
> Perhaps there is some setting I have accidentally set that prevents the controller profile actually being used?
> 
> The original Antimicro (v2.2.3) works correctly.
> 
> ### Expected Behavior
> I set buttons and keys according to my needs in AntiMicroX. I change to the game or application, and use my controller with the keybinds from AntiMicroX.
> 
> ### Steps To Reproduce
> 1. Open AntiMicroX (Using v3.4.0).
> 2. Select Load .gamecontroller.amgp
> 3. Profile is loaded in the dropdown and shows .gamecontroller in the dropdown.
> 4. Open another app, such as Calculator.
> 5. Profile in dropdown immediately changes to
> 6. Alternate method is selecting the profile directly from the dropdown instead of hitting the Load button.
> 7. The result is the same.
> 8. If a program (like Calculator) is already opened, and you then open a profile via the dropdown in AntiMicroX, and THEN switch to Calculator, the dropdown stays on .gamecontroller UNTIL you switch back to AntiMicroX, in which case it then reverts back to .
> 
> ### Environment
> ```
> Program Version 3.4.0
> Compiled from packaging: GitHub Portable Windows Release
> Built Against SDL 2.30.1
> Running With SDL 2.30.1
> Using Qt 5.15.2
> Using Event Handler: SendInput
> Host OS: windows Version: 10 Architecture: x86_64
> ```
> 
> ### Anything else?
> Here is an example video of the problem. The original Antimicro (v2.2.3) works correctly.
> 
> https://youtu.be/hp_sLsVjoAg
> 
> #### Upvote & Fund
> * If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users.
> * We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
> * Funded developer receives the funding once the issue is completed & confirmed by you.
> * Thank you in advance for helping prioritize & fund our backlog.
> 
> [ ![Fund with Polar](https://camo.githubusercontent.com/c8ef4cc2be5027e67ba7f0c617abb1f919e23e646073541d1a5b2479c82eab2f/68747470733a2f2f706f6c61722e73682f6170692f6769746875622f416e74694d6963726f582f616e74696d6963726f782f6973737565732f3933362f706c656467652e737667) ](https://polar.sh/AntiMicroX/antimicrox/issues/936)

**Comment by itsnotlevel1** [comment] 2024-11-10 20:27
My install is also doing this. I have tried to install multiple versions.... and uninstall previous.... and its not working. If I load a profile or load and save as a different version number, it doesnt stay loaded and yes I have given admin access and upon install given it path to current user and also tried all users, but it will keep reverting back to "new" as in no program loaded. The difference here is I was on a different windows computer .... windows 11 and with the windows 10 pc im on now, it keeps reverting back to "new". If i load a profile then minimize to tray, it doesnt control the cnc table I have been using it with. I hope this all makes sense.

**Comment by Mapsking** [comment] 2024-11-15 13:39
> Could you [collect some logs](https://github.com/AntiMicroX/antimicrox/wiki/Collecting-Logs) when this issue happens?
> 
> I need to check what triggers this change in your case. Maybe this may be linked with misbehaving autoprofile.

Hello @pktiuk, I just noticed this has the waiting for feedback tag. Is there something else I forgot to submit? I might have missed something, but if needed, I can provide additional things.

**Comment by pktiuk** [comment] 2024-11-17 11:39
Sorry, my bad, I forgot to temove this

**Comment by pktiuk** [comment] 2024-11-17 12:19
@Mapsking @itsnotlevel1 

Do you have autoprofile functionality enabled?

![obraz](https://github.com/user-attachments/assets/a1d93ca5-fc30-430c-b2b1-f60c2188234c)

If not please upload your AntiMicroX settings file?

`C://Users/YOURNAME/AppData/Local/antimicrox/antimicrox_settings.ini` It should in this kind of location

**Comment by Mapsking** [comment] 2024-11-17 13:35
Yes I did, actually, and perhaps I have it set incorrectly? I noticed that by disabling it, the problem no longer seems to happen. Is there a page I can look at to see specifically how to set it up correctly, or info I can provide that would be helpful to determine if it is actually a bug, or just something I've set incorrectly? I haven't used that option in a very long time, so I had forgotten I'd even set it, tbh.

**Comment by pktiuk** [comment] 2024-11-17 13:58
Firstly check this wiki page https://github.com/AntiMicroX/antimicrox/wiki/Automatically-Loading-Profiles

Auto Profile functionality is used for switching profile based on currently selected window. This is not a bug.

**Closed by pktiuk** 2024-11-17 13:58 UTC
Labels: bug

**Comment by Mapsking** [comment] 2024-11-17 14:28
Enabling/disabling did sort of solve the problem, but it is only a workaround, let me explain. (I also updated to 3.5.0, and noticed my saved auto-profiles were now gone.)

I went and looked, and have figured out the problem. In a nutshell, when you follow the directions on the wiki, and add a new profile as shown, it DOES add a new profile, as expected...
![image](https://github.com/user-attachments/assets/16c977e9-7982-457c-b441-773cc5be348a)

**HOWEVER**, it also leaves the default empty profile open. This is not indicated in the Wiki anywhere that I saw, and when the blank default profile is left open, whenever you switch windows, it removes the profile. When I add a new profile as shown here, and in the wiki, then I switch applications, it removes the profile.
![image](https://github.com/user-attachments/assets/9e33a445-d485-4bb1-977c-fe0cb95df193)

In order for this NOT to happen, I have to manually go back, and disable the default option that is set, as I can not remove it. If this is by design, it seems counter-intuitive, as logically, what any user would expect, is if I had multiple games or programs set in the auto-profile option, AntiMicroX would keep whatever profile you have loaded, until one of the specific auto profiles programs window is currently selected. If I want one profile to open when I have Calculator open, and a different profile set to open when Minesweeper is open, then when I open Notepad, it should not necessarily remove separate settings or a profile I have made for Notepad, or remove it altogether. It should only activate a specific profile when the specific specified window is open/in focus.

However, this only applies when the default auto profile (which again, you can not remove or delete), is disabled. This definitely seems like it should not be the default behavior. An easy way to fix this would simply be to disable the default profile if a new custom one is added. Also, side note, thanks very much for including a dark mode.
![image](https://github.com/user-attachments/assets/b50c92e6-1510-441a-90cf-a41e6fc785c2)
