### ISSUE TITLE
Thrustmaster TWCS throttle 8 way POV hat and 11/12/13/14 rocker not recognised

### ISSUE THREAD

**Issue by Jassida15** [AntiMicroX/antimicrox#826] opened 2023-08-26 09:20 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

AntiMicro works perfectly. X does not recognise these hats as inputs. All other axes/buttons recognised. Updated TWCS firmware/drivers. Has never worked on any AntiMicro X version or previosu win 10/11 installs. I keep trying new versions and hope for  the best. The mapping software in AMX recognises the buttons but they are not listed. I could for instance remap other buttons to these hats but they are not listed normally.

### Expected Behavior

The hats should be recognised.

### Steps To Reproduce

Try using  a TWCS  and moving these hats

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.26.5
Running With SDL 2.26.5
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment] 2023-08-26 14:26
Basically duplicate of https://github.com/AntiMicroX/antimicrox/issues/813

> Support for selected controllers is not implemented by AntiMicroX. It should be implemented in the underlying SDL library https://github.com/libsdl-org/SDL/

**Closed by pktiuk** 2023-08-26 14:26 UTC
Labels: bug

**Comment by Jassida15** [comment] 2023-08-27 21:12
Why does Antimicro work but not x then? Please help me understand how to
use SDL. Thank you
