### ISSUE TITLE
Xbox one controller won't reconnect for more than a second and then shuts off

### ISSUE THREAD

**Issue by koga-ninja** [AntiMicroX/antimicrox#663] opened 2022-12-16 17:12 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When I launch the portable program everything works fine.  Once my controller shuts down from no use when I try to reconnect the program shows a connection for a quick second and then disconnects as my controller shuts off.  This has occurred on two different computers with different controllers.  Relaunching the program allows the remote to reconnect.
Thanks in advance for any help!

### Expected Behavior

Reconnect without needing to restart program.

### Steps To Reproduce

Open program.
Power off controller.
Turn controller back on.

**Comment by ZeptoBST** [comment] 2022-12-16 17:43
Are you using the Xbox Wireless Adapter? If so, it's a bug with the version of SDL they use.

**Comment by koga-ninja** [comment] 2022-12-16 18:12
@ZeptoBST 

> Are you using the Xbox Wireless Adapter? If so, it's a bug with the version of SDL they use.

Yes, I use the Xbox chatpad as a keyboard. Any work around? I didn’t have the issue on the original antimicro app.

**Comment by pktiuk** [comment] 2022-12-16 18:15
@ZeptoBST  Could you mention this SDL issue here? (For the sake of good navigation)

@koga-ninja  You could try to install an older AntiMicroX version.

**Comment by koga-ninja** [comment] 2022-12-16 21:18
@pktiuk Okay, I may have to try that. At the moment I'm going to assign a killtask.exe to the controller power button so it shuts down microx when I'm turning the controller on. Then I have a shortcut from the keypad to bring it back online. If not I'll go back to an older version, any idea what version may work with Xbox accessories?

**Comment by koga-ninja** [comment] 2022-12-16 21:20
> @pktiuk Okay, I may have to try that. At the moment I'm going to assign a killtask.exe to the controller power button so it shuts down microx when I'm turning the controller on. Then I have a shortcut from the keypad to bring it back online. If not I'll go back to an older version, any idea what version may work with Xbox accessories?

No luck, it doesn't connect long enough to send the command.

**Comment by ZeptoBST** [comment] 2022-12-16 23:32
Here is a previous thread containing the link: [https://github.com/AntiMicroX/antimicrox/issues/581](url)

Also, the only workaround for me was to use the original AntiMicro. I downloaded the source code for AntiMicro and built it myself so I could fix things in the event something goes wrong (I guess).

**Comment by pktiuk** [comment] 2022-12-17 01:35
Until  https://github.com/libsdl-org/SDL/issues/3468 won't be fixed you can try to compile antimicrox with older SDL (like `2.0.12`).

**Comment by pktiuk** [comment] 2022-12-17 12:05
@ZeptoBST   
> Also, the only workaround for me was to use the original AntiMicro. I downloaded the source code for AntiMicro and built it myself so I could fix things in the event something goes wrong (I guess).

I think you could also try to compile old, legacy `AntiMicro` code with new SDL to check whether new SDL is the root cause or the app

**Comment by ZeptoBST** [comment] 2022-12-17 16:51
@pktiuk Ok, so I compiled the old AntiMicro with SDL 2.26.1 and yes, the issue does occur now, so SDL is indeed the problem.

Another problem I've noticed however is that when using 2.26.1, it no longer loads the previously used profile and just loads a "New" template instead. No such problem with SDL 2.0.5.

**Comment by pktiuk** [comment] 2022-12-18 22:18
Ok in this case we are now sure, that this bug is out of the scope of AntiMicroX.    

When https://github.com/libsdl-org/SDL/issues/3468  will be solved I will just update SDL version to include fix.

**Closed by pktiuk** 2022-12-18 22:18 UTC
Labels: bug

**Comment by koga-ninja** [comment] 2022-12-20 04:24
Appreciate you all looking into it. For some odd reason it does eventually connect if I keep turning the controller on. Sometimes on the second try sometimes on the tenth, haha. Anyways I'll work around it for now. Thanks again..

**Comment by pktiuk** [comment] 2022-12-20 10:16
To increase the probability of solving that issue quickly you could provide SDL developers a nominal working example showing this bug and in general, assist them with finding the root cause, but it requires some C/C++ skills.

**Comment by koga-ninja** [comment] 2022-12-21 03:39
If you have any guidance on who to submit it to and where to start on how to capture the problem I would give it a shot. Thanks

**Comment by pktiuk** [comment] 2022-12-21 07:22
I gave you link to the issue https://github.com/libsdl-org/SDL/issues/3468 . This is your starting point. You have to figure this out by yourself. You can also ask there, but firstly carefully read the description, because there may be some clues.

**Comment by koga-ninja** [comment] 2022-12-21 19:56
That link is very promising! Thanks again.

**Comment by koga-ninja** [comment] 2023-01-11 18:08
> 

@ZeptoBST,  Hello again.  I've been hoping to research and start working on this issue for myself but have not had time, would there be a possibility you could upload your version so I could give it a try?  I don't have much knowledge on the programming side as of yet...

**Comment by kanedauy** [comment] 2023-05-29 23:44
@pktiuk Seems that SDL fixed the issue https://github.com/libsdl-org/SDL/issues/3468#issuecomment-1567561092

**Comment by pktiuk** [comment] 2023-05-30 06:54
Great, now we wait for release with this fix.

**Comment by pktiuk** [comment] 2023-06-22 20:23
Then this fix will appear in the next release of AntiMicroX

**Comment by koga-ninja** [comment] 2023-07-07 13:16
https://github.com/libsdl-org/SDL/issues/7940#issuecomment-1625040863

Updating the SDL leads to the Xbox controller triggers not working without another button input simultaneously.

**Comment by pktiuk** [comment] 2023-07-13 14:55
@koga-ninja   

What is the latest SDL version without this bug?

**Comment by koga-ninja** [comment] 2023-07-13 15:06
SDL 2.28.1.

**Comment by lukasva77** [comment] 2023-08-08 03:16
so anyone have installer with sdl 2.28.2 for windows I have never build anything in my life
koga-ninja maybe

**Comment by pktiuk** [comment] 2023-08-08 11:29
Maybe next week I will prepare one, if I will find some time.

**Comment by pktiuk** [comment] 2023-08-26 20:29
I created a pre-release bundled with the latest SDL2. You can test it. And let me know whether everything works now.
https://github.com/AntiMicroX/antimicrox/releases/tag/3.3.4-updated-SDL

**Comment by lukasva77** [comment] 2023-08-31 00:03
I've done the manual replacement before this release but there is still one bug left with newest xbox controller and 2nd gen xbox wireless
when controller shuts off it seems the triggers get used for instance I have left mouse and right mouse on triggers if mouse is pointing at something like video surface that means it gets unpaused and happily keep playing right clicks are generally harmless if this is SDL bug someone should report it so it will be perfect if it gets fixed
thanks pktiuk for your work
and thank you koga-ninja for all this work for people who have this obvious xbox combo
