### ISSUE TITLE
Set selection/toggling across multiple devices

### ISSUE THREAD

**Issue by azaghal** [AntiMicroX/antimicrox#1095] opened 2024-11-20 11:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When playing space simulations with HOTAS (Thrusmaster T.16000 FCS HOTAS in particular - throttle and joystick), I find it frustrating that I cannot switch the set for both devices at the same time using button from only one of the connected devices.

### Describe the solution you'd like

I would like to be able to:

- Switch to a different set on all connected devices at the same time using a single button from just one of the devices.
- Switch to a different set on device 2 using a button from device 1.

### Describe alternatives you've considered

- Using a dedicated button on joystick controller - this is not really feasible because it does not have buttons on the stick that can be held with pinky/ring/middle fingers (unlike the throttle counterpart).
- Exposing HOTAS as unified device to AntiMicroX (not aware of something like this being available under GNU/Linux).
- Switching device set via AntiMicroX CLI (cannot see any way to control this when in daemon mode).

### Additional context

In particular, I am currently playing X4: Foundations space sim, which has quite a lot of controls, and is somewhat limited at the way those controls can be bound in-game (it's a bit of a mix). The use of AntiMicroX with secondary sets has helped tremendously by letting me have secondary controls on the throttle itself, but this is also not necessarily the most ergonomic solution.

Being able to use both hands (left for set toggling, right for pressing the button) would make it a bit easier on the hands - since my right hand thumb is both a bit more agile, and the controls on top of the joystick are kinda more accessible compared to the throttle ones.

The closest related issue I have seen was #293 - but I do not really need to unify the HOTAS for this particular game - I merely need to be able to change (while button is held) the set on both connected devices at the same time.

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1095">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1095/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1095/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment] 2024-11-24 14:01
Duplicate of: #164 

https://github.com/AntiMicroX/antimicrox/issues/164#issuecomment-981134249

**Closed by pktiuk** 2024-11-24 14:01 UTC
Labels: enhancement
