### ISSUE TITLE
Xbox One Controller immediately disconnects if connecting it a second time.

### ISSUE THREAD

**Issue by Ragster2448** [AntiMicroX/antimicrox#791] opened 2023-06-01 06:36 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

After connecting my Xbox One controller to my PC, disconnecting the controller, then attempting to reconnect my controller a second time, the controller will immediately disconnect after connecting. I see the profile tab appear in AntiMicroX for a split second before it disconnects. I cannot connect my controller again until I close AntiMicroX. Reopening the program allows me to connect the controller, but repeats the issue on consecutive connects.

I have tested this while no profile was loaded, still with the same result.

Xbox One Wireless Controller + Xbox Wireless Adapter for Windows 10

### Expected Behavior

Should be able to connect and disconnect the same controller without closing and reopening AntiMicroX every time.

### Steps To Reproduce

1. Start AntiMicroX.
2. Connect controller.
3. Disconnect controller.
4. Connect controller.
5. Controller is immediately, and automatically, disconnected.

### Environment

```markdown
Program Version 3.3.3
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment] 2023-06-01 07:35
Seems to be duplicate of https://github.com/AntiMicroX/antimicrox/issues/663

**Closed by pktiuk** 2023-06-01 07:35 UTC
Labels: bug
