### ISSUE TITLE
Add numpad buttons

### ISSUE THREAD

**Issue by opgyerek** [AntiMicroX/antimicrox#529] opened 2022-08-31 12:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The software has no support for numpad buttons.

### Describe the solution you'd like

Just add numpad buttons.

### Describe alternatives you've considered

none. 

### Additional context

![image](https://user-images.githubusercontent.com/55882778/187678941-0574bfa3-72b9-4bb5-bae4-24ff92604af8.png)

**Comment by instinctualjealousy** [comment] 2022-11-30 17:38
Go into the Settings and check "Attach numeric keypad". You didn't have to do this in old builds.

**Comment by pktiuk** [comment] 2022-11-30 17:52
> Go into the Settings and check "Attach numeric keypad". You didn't have to do this in old builds.

It seems, that someone knows this app better than me ;)  
But existence of this issue shows, that it would be better if this setting would be also visible in the assignment dialog.

**Comment by pktiuk** [comment] 2022-12-01 12:18
It apperas to be also a duplicate of https://github.com/AntiMicroX/antimicrox/issues/168

**Closed by pktiuk** 2022-12-01 12:18 UTC
Labels: enhancement
