### ISSUE TITLE
Mouse Click In selected area of Monitor

### ISSUE THREAD

**Issue by Papermanzero** [AntiMicroX/antimicrox#502] opened 2022-07-31 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

It would be cool to define certain coordinates on the monitor for a mouse button click.
This could help to click on certain areas in a menu or in ingame without moving the mouse cursor to that coordinates. 

### Describe the solution you'd like

Define virtual mouse clicks o. the monitor

**Comment by pktiuk** [comment] 2022-07-31 20:59
Duplicate of: https://github.com/AntiMicroX/antimicrox/issues/154

**Closed by pktiuk** 2022-07-31 20:59 UTC
Labels: duplicate, enhancement
