### ISSUE TITLE
Unusually long launch time

### ISSUE THREAD

**Issue by jackj1** [AntiMicroX/antimicrox#730] opened 2023-02-19 23:10 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Program takes anywhere from 2 seconds to up to a minute to launch after execution

### Expected Behavior

To launch much quicker

### Steps To Reproduce

1. execute program
2. launch is usually around 15 seconds, but is occaisionally instantaneous or up to a minute before the main window or the taskbar applet show up

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb 19 2023 at 21:31:29
Built Against SDL 2.26.3
Running With SDL 2.26.3
Using Qt 5.15.8
Using Event Handler: XTest
Compositor type: tty
Host OS: artix Version: unknown Architecture: x86_64
```

### Anything else?

passing `--log-level verbose` doesn't show any unexpected behaviour, but worth mentioning that the line it hangs on is `🟢INFO  "Using XTest as the event generator."`

Here are the relevant lines of the log:

<pre><code>❗WARN  QCommandLineParser: option not defined: "next"
⚪VERBOSE       AntiMicroX version: 3.3.3 Type: Release
⚪VERBOSE       SDL version: 2.26.3 (Compiled with: 2.26.3)
⚪VERBOSE       Host OS: artix Version: unknown Architecture: x86_64
🟢INFO  "Using XTest as the event generator."
🟢INFO  Created new GameController:
                        Index:            1</code></pre>

**Comment by pktiuk** [comment] 2023-02-20 00:05
Could you also get logs with debug level (maybe app will freeze on another log)?

Could you also test it with appimage version?

**Comment by jackj1** [comment] 2023-02-20 10:20
Sure thing, here is the debug log, in this case it took about 22 seconds from execution to launch.
[antimicrox.log](https://github.com/AntiMicroX/antimicrox/files/10783260/antimicrox.log)

And I've tested the appimage version, it works much faster, launches in under half a second. i'll attach the debug log for that aswell just incase comparing them helps you.
[antimicrox-appimage.log](https://github.com/AntiMicroX/antimicrox/files/10783324/antimicrox-appimage.log)

**Comment by pktiuk** [comment] 2023-02-20 10:27
I think the problem is with that SDL version, not with the app itself.

**Comment by pktiuk** [comment] 2023-02-23 18:46
You can also try to extract antimicrox binary from AppImage `./AntiMicroX-x86_64.AppImage --appimage-mount` and replace the one installed by your package manager. And if everything will work well after replacement, then it means that package in your distro repo is broken (and you have to contact with package maintainer). But if everything will be fixed, then it means, that another dependency in your OS is broken (this is also out of my scope). 

BTW, You should know that I do not support packages from atrix. The only supported ones are: deb, AppImage and Flatpak

**Closed by pktiuk** 2023-02-23 18:46 UTC
Labels: bug

**Comment by pktiuk** [comment] 2023-02-23 18:48
If you will contact maintainer you could also let him know, that she should use compilation flag `ANTIMICROX_PKG_VERSION` to properly mark source of the package.
