### ISSUE TITLE
Strange bugs on Fedora

### ISSUE THREAD

**Issue by Nokia808** [AntiMicroX/antimicrox#57] opened 2020-10-03 06:57 UTC
Hi. I installed this program from official Fedora repositories after remove antimicro from my system.

I noticed strange bugs that I do not know how to explained but I feel that they related to one other:

1) when I installed antimicrox it's launcher icon do not appear in application menu as BOLD. It should appear in bold before 1st launching .....
2) during my launch / exit it crashed at an occasion.
3) here is strange thing: I switched ON my laptop & during DE loading I listened to sound of system notification ! When DE launched & appeared I saw system error message !!! How this ? Does antimicrox working as a service ??

I'm on Fedora 32 X64 bit Cinnamon edition with AntiMicroX 3.1.0 and just now AntiMicroX crashed after I launched it to see it's version then exit it ! It crashed after I exit it .....

**Comment by gombosg** [comment] 2020-10-03 17:07
Hi, thanks for reporting.
This might not be Fedora-specific.
First off, you can try installing this [testing update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-19f2e35d99).

> when I installed antimicrox it's launcher icon do not appear in application menu as BOLD. It should appear in bold before 1st launching .....

This is a minor issue, and probably doesn't have anything to do with packaging.

> during my launch / exit it crashed at an occasion.

What does crash mean? How can it be reproduced? Do you have any error logs? Does it crash when starting from terminal `antimicrox`?

> here is strange thing: I switched ON my laptop & during DE loading I listened to sound of system notification ! When DE launched & appeared I saw system error message !!! How this ? Does antimicrox working as a service ??

Did the notification come from antimicrox? What does the error say?

**Comment by Nokia808** [comment] 2020-10-05 06:31
@gombosg 
Hi. It is system error, saying that "Oop! It seem that AntiMicroX crash .....". I did not generate error report.
I did not tried launching from terminal .... I will try ..... .
It is unpredictable! It may appear by launch application / exit / relaunch it ....

**Comment by Nokia808** [comment] 2020-10-30 11:57
Hi. Bug is still existing even after updating to last version.

Moreover, I encountered crash while I was play a game (cave9) ! This make application loss too of it's usefulness ....

**Comment by pktiuk** [comment] 2020-10-30 15:38
We can't do too much without any logs or reproduction steps.  
Because of https://github.com/AntiMicroX/antimicrox/issues/78 the only possibility to obtain logs in file is running app via with --log-level flag, for example: `antimicrox --log-level debug 2>/tmp/antimicrox.log`

To do it a bit more convenient for daily use you could edit file `/usr/share/applications/io.github.antimicrox.antimicrox.desktop 
` and update line number 11 to:
```
Exec=antimicrox --log-level debug 2>/tmp/antimicrox.log
```

Thanks to this after next crash you could send us logs from this file (but remember that after every launch this file is overwritten, so don't launch antimicrox again before sending this file to us, moreover after restarting your pc this file will be also removed to avoid making mess :) )

**Comment by gombosg** [comment] 2020-11-15 18:36
I'm closing this issue do to lack of repro. Adding some input will reopen automatically.

**Closed by gombosg** 2020-11-15 18:36 UTC
Labels: bug
