### ISSUE TITLE
WARN QCommandLineParser: option not defined: "next"

### ISSUE THREAD

**Issue by asdf23** [AntiMicroX/antimicrox#772] opened 2023-04-20 19:59 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

When changing profiles via the command line (antimicrox -- profile ~/myFile.gamecontroller.amgp) I get this error 
!WARN   QCommandLineParser: option not defined: "next"
AntiMicroX is already running.

### Expected Behavior

This warning should not appear.  "next" does not seem to be a valid command line parameter.

### Steps To Reproduce

change the profile from command line with
`antimicrox --profile ~/myFile.gamecontroller.amgp`

### Environment

```markdown
Program Version 3.3.3
Program Compiled on Feb 13 2023 at 00:00:00
Built Against SDL 2.26.2
Running With SDL 2.26.3
Using Qt 5.15.9
Using Event Handler: XTest
Compositor type: x11
Host OS: fedora Version: 37 Architecture: x86_64
```

**Comment by asdf23** [comment] 2023-04-20 20:12
This is working in:

Program Version 3.3.3
Program Compiled on Feb 13 2023 at 00:00:00
Built Against SDL 2.26.2
Running With SDL 2.26.3
Using Qt 5.15.8
Using Event Handler: XTest
Compositor type: x11
Host OS: fedora Version: 36 Architecture: x86_64

**Comment by pktiuk** [comment] 2023-04-20 20:38
Duplicate of: https://github.com/AntiMicroX/antimicrox/issues/189

**Closed by pktiuk** 2023-04-20 20:38 UTC
Labels: bug

**Comment by oldtools** [comment] 2023-07-16 03:51
What would be the command line option to assign profiles to joysticks if the "next" option is removed?

**Comment by pktiuk** [comment] 2023-07-25 13:49
@oldtools `--next` option is not working anyway (i don't know why it was broken or whether it worked at all). And nobody complained about this, so I assume it is not needed by anyone
