### ISSUE TITLE
AntimicroX crash

### ISSUE THREAD

**Issue by Raniuss** [AntiMicroX/antimicrox#163] opened 2021-04-30 10:18 UTC
Goodmorning everyone,
I am using Ubuntu and with antimicro everything perfect without any problem but, AntimicroX at some point closes, it gives this error Even on Arch systems, How can it be solved? But above all, in what language is it written?

Sincerely

`ranius@ranius:/usr/bin$ cd
ranius@ranius:~$ sudo antimicrox
[sudo] password di ranius: 
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: Empty filename passed to function ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Warning: RECEIVED ((null):0, (null))
Warning: all current slots and previous slots ale cleared ((null):0, (null))
Errore di segmentazione
`

**Comment by gombosg** [comment] 2021-04-30 12:50
Hi, thanks for the report.

`Errore di segmentazione`
Looks like a segfault...
It's written in C++.
Can you reproduce the issue consistently?

**Comment by Raniuss** [comment] 2021-04-30 12:56
No, because I was actually using it as a mouse and it suddenly crashes

**Comment by Raniuss** [comment] 2021-05-01 09:06
At that precise moment nothing special, I was just moving the joystick so as to make the pointer move on the screen I cannot tell you when the error occurs simply because this step is variable, sometimes it closes immediately, other times after two hours of use

**Comment by mvvvv** [comment] 2021-05-01 09:51
And it crash too often :

[_usr_bin_antimicrox.1000.crash.txt](https://github.com/AntiMicroX/antimicrox/files/6409334/_usr_bin_antimicrox.1000.crash.txt)

**Comment by Raniuss** [comment] 2021-05-01 14:42
There's just one small problem: I can't find that file within that path

**Comment by mvvvv** [comment] 2021-05-01 16:23
the file is under /var/crash/ without the .txt suffix that I added to upload it here.

**Comment by Raniuss** [comment] 2021-05-01 16:56
x-special/nautilus-clipboard
copy
file:///var/crash/_usr_bin_antimicrox.1000.crash

**Comment by Raniuss** [comment] 2021-05-01 17:00
[_usr_bin_antimicrox.1000.odt](https://github.com/AntiMicroX/antimicrox/files/6409981/_usr_bin_antimicrox.1000.odt)

**Comment by mvvvv** [comment] 2021-05-05 13:58
I've installed the 3.1.5 ubuntu package from here and ... crash again
[_usr_bin_antimicrox.1000.crash.txt](https://github.com/AntiMicroX/antimicrox/files/6427637/_usr_bin_antimicrox.1000.crash.txt)

**Comment by pktiuk** [comment] 2021-08-19 16:08
Closing as a duplicate of https://github.com/AntiMicroX/antimicrox/issues/133 

(I prefer having all of crashes and comments in one place)

**Closed by pktiuk** 2021-08-19 16:08 UTC
Labels: bug
