### ISSUE TITLE
Shortcuts to Switch to a Set

### ISSUE THREAD

**Issue by SarahSzabo** [AntiMicroX/antimicrox#773] opened 2023-04-22 08:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Allow the user to set a control sequence for changing to a certain profile.

I plan on using an integrated system for controlling my computer using foot pedals and a flight controller, but it's hard to switch profiles on the foot pedals, so doing so with a button on the flight stick would be great.

### Describe the solution you'd like

Flight controller button -> switch set to 1 & SUPER + 1 (shortcut for switching foot pedal to set 1).

Probably a setter on each set which allows a user to set a keyboard shortcut to immediatly switch to that set.

**Comment by pktiuk** [comment] 2023-04-22 13:28
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/298

**Closed by pktiuk** 2023-04-22 13:28 UTC
Labels: enhancement
