### ISSUE TITLE
Realign Center for Spring Mouse Mode

### ISSUE THREAD

**Issue by rorybd** [AntiMicroX/antimicrox#822] opened 2023-08-12 21:25 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the solution you'd like

When setting a joystick to control the mouse, there is a 'spring' mode that centers the mouse when you let go of the joystick.

It would be great if there was a way to move the region that the cursor can move within when in spring mode, for instance to the side of the screen.
![image](https://github.com/AntiMicroX/antimicrox/assets/124809440/30946f1c-90a9-49c3-a4bf-5eb3b285fc1b)

**Comment by pktiuk** [comment] 2023-08-13 22:55
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/648

Checkbox ` I have searched the existing issues` placed here has its purpose.

**Closed by pktiuk** 2023-08-13 22:55 UTC
Labels: enhancement
