### ISSUE TITLE
antimicro key values do not match any of the Qt key values, unable to set keybinds.

### ISSUE THREAD

**Issue by ricc0chet** [AntiMicroX/antimicrox#1018] opened 2024-08-10 03:48 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Cannot set keybinds with keyboard, the anitmicro key value does not match the Qt key value for any key pressed.

### Expected Behavior

I want to assign a combination of buttons to button presses, (Ctrl + 1) but pressing the 1 key does not match the value that antimicrox puts in the button assignments. The virtual keyboard in antimicrox works, but it isn't available in the advanced button assignment

### Steps To Reproduce

1. Click button for assignment
2. use the virtual keyboard for the initial button press
3. click the advanced button
4. press the next key on the keyboard
5. wrong value shows up in the editor

### Environment

```markdown
Program Version 3.4.0
Program Compiled on Apr  7 2024 at 00:00:00
Built Against SDL 2.30.1
Running With SDL 2.30.3
Using Qt 5.15.14
Using Event Handler: uinput
Compositor type: wayland
Host OS: nobara Version: 40 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1018">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1018/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1018/pledge.svg">
</picture>
</a>

**Comment by foldfree** [comment] 2024-09-01 11:26
duplicate of https://github.com/AntiMicroX/antimicrox/issues/721

**Closed** 2024-09-01 12:25 UTC
Labels: bug, duplicate
