### ISSUE TITLE
Xbox Share button not being detected

### ISSUE THREAD

**Issue by DomoTurbulence** [AntiMicroX/antimicrox#538] opened 2022-09-30 19:29 UTC
Windows now supports the xbox share button (new button in the middle of the Series S/X controller). Could you update AntiMicroX to detect this input too please? Thanks!

**Comment by pktiuk** [comment] 2022-10-10 13:12
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/307

**Closed by pktiuk** 2022-10-10 13:12 UTC
