### ISSUE TITLE
Buttons on Dualsense controller

### ISSUE THREAD

**Issue by Buzbee** [AntiMicroX/antimicrox#847] opened 2023-10-13 21:32 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

Buttons 17-20 are listed for PS5 Dualsense but I cannot determine what they are. I assume maybe swipe up down left and right. It does not seem to be implemented. Button 21 is the touchpad button.

### Expected Behavior

button press

### Steps To Reproduce

None

### Environment

```markdown
Program Version 3.3.4
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.28.2
Running With SDL 2.28.2
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment] 2023-10-13 22:27
This is duplicate of https://github.com/AntiMicroX/antimicrox/issues/582   
By default every gamepad has hardcoded number of buttons. Fixing this will require some refactoring and unluckily I don't have much spare time in this year to fix this.

**Closed by pktiuk** 2023-10-13 22:27 UTC
Labels: bug
