### ISSUE TITLE
Valorant Cursor Not Working

### ISSUE THREAD

**Issue by JKP5758** [AntiMicroX/antimicrox#738] opened 2023-03-05 08:07 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

cursor not working

### Expected Behavior

The cursor should be able to move to look around

### Steps To Reproduce

why doesn't mouse work when playing Valorant? Even though when in the lobby everything looks fine, the cursor can still move. but when the round started I couldn't move the crosshair. right and left click still works, it's just that the crosshair doesn't work. when opening the shop, the cursor still works, and looks normal. but when closing the shop, the crosshair still doesn't move

### Environment

```markdown
Program Version 3.3.3
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment] 2023-03-05 11:09
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/406

**Closed by pktiuk** 2023-03-05 11:09 UTC
Labels: bug
