### ISSUE TITLE
[Feature request]Simplifying support for Bluetooth

### ISSUE THREAD

**Issue by OlegPopow** [AntiMicroX/antimicrox#33] opened 2020-09-11 23:08 UTC
Much of the good quality pads now work wirelessly. Do you plan to add such functionality in the program? The era of wired pads is slowly coming to an end and relatively soon only the cheapest crap will be available in a wired version. If possible, I would like to ask for an answer and not just give a flag.

**Comment by OlegPopow** [comment] 2020-09-12 00:06
Although I found information that AntiMicro/AntiMicroX MAY handle such pads, I found a lot of threads that clearly indicate that so far it is not working as it should. This requires a lot of effort, which may discourage potential users.

Perhaps you should think about writing appropriate tips or find some way to make it easier.

**Comment by pktiuk** [comment] 2020-09-12 07:11
But AntimicroX already supports Bluetooth controllers, they use the same protocols as the rest of HID devices.

I am using it with my BT gamepad and it works without any problem.

**Comment by OlegPopow** [comment] 2020-09-12 11:15
But I wrote that the pad will probably work. I only wrote later that from the information I found on the old Antimicro it can sometimes be very problematic and maybe there would be a way to make it easier.

**Comment by pktiuk** [comment] 2020-09-12 12:03
There are no issues connected with using BT devices reported yet.

**Comment by OlegPopow** [comment] 2020-09-12 12:14
I suggested this [1]. By the way, you don't have reports because too few people know where to report bugs now. Patience :D 

[1] https://github.com/AntiMicro/antimicro/issues?q=bluetooth

Again, as I wrote, I'm not saying that AntiMicroX doesn't support it at all, only that TIME is sometimes problematic. It would be worth to write some short HOW TO write.

**Comment by gombosg** [comment] 2020-09-12 12:48
Thanks! Yes, I see those issues for antimicrox. It's hard to even triage these old, stale issues, let alone test them. (Also, the latest [issue](https://github.com/AntiMicro/antimicro/issues/300) is for Windows and we don't [yet] have a build for it.)

But if someone manages to open an issue here with a clear, testable situation, like some common wireless controller not working, then we can move on, test and hopefully fix it.

**Comment by pktiuk** [comment] 2020-09-12 19:41
Due to lack of clearly defined, and reproducible issues with BT controllers I am closing this issue.

**Closed by pktiuk** 2020-09-12 19:41 UTC
