### ISSUE TITLE
Identifies as a trackpad

### ISSUE THREAD

**Issue by dam0ngus** [AntiMicroX/antimicrox#675] opened 2022-12-27 01:15 UTC
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

on valorant you cannot use a trackpad as a mouse and this program identifies it as a trackpad pls fix

### Steps To Reproduce

1 bind stick to mouse 
2 open valorant 
3 go into practice range
4 you wont be able to look around

### Environment

```markdown
Program Version 3.3.2
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

**Comment by pktiuk** [comment] 2022-12-27 16:33
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/406

**Closed by pktiuk** 2022-12-27 16:33 UTC
Labels: bug
