### ISSUE TITLE
Config file not loading

### ISSUE THREAD

**Issue by Vitorvlv** [AntiMicroX/antimicrox#622] opened 2022-11-20 03:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Antimicrox is not loading a working config file.

### Expected Behavior

It loads the config file

### Steps To Reproduce

Load config file

### Environment

```markdown
- OS: Fedora 37
- AntiMicroX version: 3.3.1 from flathub
```

### Anything else?

If I use the antimicrox available on the repositories  (3.2.4) it works. 

Short videos showing it not working on the latest antimicrox, and another one showing it working on the older version.

[flatpak.webm](https://user-images.githubusercontent.com/26132870/202883118-64a5ca54-6cba-46e9-9114-3c0e3f6f9b87.webm)

[older version.webm](https://user-images.githubusercontent.com/26132870/202883092-737036b5-ca79-476a-8e7f-6cd1be800f48.webm)

I've just tried with the 3.3.1 appimage too, to rule out something wrong with the flatpak, and it also doesn't work.

**Comment by pktiuk** [comment] 2022-11-20 15:14
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/618  
Before opening new issue please firstly search for similar issues.

**Closed by pktiuk** 2022-11-20 15:14 UTC
Labels: bug
