### ISSUE TITLE
Move the mouse to the specified coordinates

### ISSUE THREAD

**Issue by keqingf** [AntiMicroX/antimicrox#1014] opened 2024-07-31 17:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

 I want to set a key to move the mouse to a specified position and left-click. How can I achieve this functionality?

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1014">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1014/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1014/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment] 2024-07-31 20:50
Duplicate of issue: https://github.com/AntiMicroX/antimicrox/issues/154

**Closed by pktiuk** 2024-07-31 20:50 UTC
Labels: enhancement
