### ISSUE TITLE
profiles reset 

### ISSUE THREAD

**Issue by jamilbowey** [AntiMicroX/antimicrox#616] opened 2022-11-16 18:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

profiles will revert to default settings each boot up

### Expected Behavior

profiles should save ready to go on start but doesn't save at all

### Steps To Reproduce

change and create a profile 
restart computer 
profiles are all default 

### Environment

```markdown
- OS:
- AntiMicroX version:
```

**Comment by pktiuk** [comment] 2022-11-16 18:51
You forgot to fill your environment

**Comment by jamilbowey** [comment] 2022-11-16 19:12
How do I do that?

**Comment by pktiuk** [comment] 2022-11-16 22:01
@jamilbowey   
This part of your raport is empty. 
```
- OS:
- AntiMicroX version:
```

**Comment by jamilbowey** [comment] 2022-11-21 23:08
windows 11
antimicro 3.3.1

**Comment by pktiuk** [comment] 2022-11-22 07:13
Then retest with the latest version.

**Comment by pktiuk** [comment] 2022-11-22 15:52
Duplicate of https://github.com/AntiMicroX/antimicrox/issues/618

**Closed by pktiuk** 2022-11-22 15:52 UTC
Labels: bug, waiting for feedback
